version: "3"

env:
  name: "CartPole-v0"
  count: 1
  episode_count: 100
  max_step: 300
  train_every_episode: 1
  render: False

model:
  name: "ql_table"
  action_dim: 2
  epsilon: 0.3
  path: "./ql_table_model.hd5"

train:
  name: "ql_table_train"
  save_model_every_episode: 10
  lr: 0.01
  reward_decay: 0.9
  e_greedy: 0.9
  gamma: 0.5


